name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install && cd ./frontend && npm install
      
      - name: Check style
        run: npm run lint

      - name: Build
        run: npm run build:ui
      
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: |
            npm run start:test
            npm run start-prod
          wait-on: http://localhost:5173

  deploy_to_fly:
    if: ${{ github.event_name == 'push' && !contains((github.event.commits.*.message), '#skip') }}
    needs: build_and_test
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Fly deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}


      